wandb_version: 1

learning_rate:
  desc: null
  value: 1.0
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709304226.367414
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
