wandb_version: 1

learning_rate:
  desc: null
  value: 5.1545225121833286e-05
epochs:
  desc: null
  value: 2
gamma:
  desc: null
  value: 0.34892049174241024
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709635922.386787
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
